#Curso de Dados Udemy

##Sétima Seção - Prática em Python

###Variáveis e Objetos

In [1]:
x = 1
print(x)

y = 3.13
print(y)

m = "Python"
m = 'Python'
print(m)

w = True
y = False
print(y)

1
3.13
Python
False

In [2]:
x = 10
y = 20
z = 100
w = ( (x+y) * z) /100
print(w)

30.0

In [3]:
print("Este texto será impresso no console")
print(x)
print("Texto e duas variáveis", x , ",",z)

Este texto será impresso no console
10
Texto e duas variáveis 10 , 100

In [4]:
print(type(x))
print(type(m))

<class 'int'>
<class 'str'>

In [5]:
print("Informe o valor:")
i = input()
print(type(i))

Informe o valor:
10
<class 'str'>

In [6]:
print("Informe o valor:")
i = input()
# i = input("Informe o valor: ")

Informe o valor:
2

In [7]:
#Converter para inteiro
var = input("Informe o valor:")
print(type(var))
var = int(var)
print(type(var))

Informe o valor:20
<class 'str'>
<class 'int'>

In [8]:
#Converter para float
var = input("Informe o valor:")
print(type(var))
var = float(var)
print(type(var))

Informe o valor:20
<class 'str'>
<class 'float'>

###Estrutura de Condição

In [11]:
nota = 7
if(nota >= 6):
  print("Aprovado")
elif(nota == 5):
  print("Recuperação")
else:
  print("Reprovado")

Aprovado

###Estrutura de Repetição

In [12]:
count = 1
while count <= 5:
  print(count)
  count += 1

1
2
3
4
5

In [13]:
for n in range(0,10):
  print(n+1)

for n in range(0,11):
  print(n)

1
2
3
4
5
6
7
8
9
10
0
1
2
3
4
5
6
7
8
9
10

###Listas

In [14]:
lst = [1,2,3,4,5]
print(lst)

lst2 = [1,2,3,"4",True]
print(lst2)

lst3 = [12,[1,2,3,4,5],"a"]
print(lst3)

lst4 = list(range(0,10))
print(lst4)

print(len(lst))

print(lst[0])

for n in range(0,len(lst4)):
  print(lst4[n]+1)

[1, 2, 3, 4, 5]
[1, 2, 3, '4', True]
[12, [1, 2, 3, 4, 5], 'a']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
5
1
1
2
3
4
5
6
7
8
9
10

###Dicionários,Sets e Tuplas

In [23]:
Notas = {'João':6.0,'Maria':8.0,'Pedro':6.5}
print(Notas)
print(Notas['João'])

Notas.keys()
Notas.values()

print('João' in Notas)
print('Fernando' in Notas)

del Notas['João']
print(Notas)

Notas['Ana'] = 9
print(Notas)

Notas.get('Geraldo',"Não encontrado!")

bigdata = {'Spark','Hive','Sqoop'}
print(bigdata)

bigdata.add('Hadoop')
print(len(bigdata))

{'João': 6.0, 'Maria': 8.0, 'Pedro': 6.5}
6.0
True
False
{'Maria': 8.0, 'Pedro': 6.5}
{'Maria': 8.0, 'Pedro': 6.5, 'Ana': 9}
{'Sqoop', 'Spark', 'Hive'}
4

###Funções

In [21]:
def imprime():
  print("esta é uma função")

imprime()

print("====================================")

def imprime(n):
  print(n)

imprime("Novo conteúdo")

print("====================================")

def potencia(n):
  return n * n

x = potencia(4)
print(x)

print("====================================")

def intervalo(inic = 1,fim=10):
  for inic in range(1,fim+1):
    print(inic)

x = intervalo(1,10)
y = intervalo()

print("====================================")

print(abs(-200))
lst = [1,2,30,35,40]
print(max(lst))
print(min(lst))
print(sum(lst))

esta é uma função
====================================
Novo conteúdo
====================================
16
====================================
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10
====================================
200
40
1
108

###Módulos e Pacotes

In [24]:
import statistics

z = [10,20,30,40]
x = statistics.mean(z)
y =  statistics.median(z)

print(x,y)

import statistics as est

z = [10,20,30,40]
x = est.mean(z)
y =  est.median(z)

print(x,y)

from statistics import mean,median
z = [10,20,30,40]
x = mean(z)
y = median(z)
print(x,y)

from statistics import *
z = [10,20,30,40,50]
x = mean(z)
y = median(z)
print(x,y)

25 25.0
25 25.0
25 25.0
30 30

###Numpy

In [26]:
import numpy as np

In [29]:
#cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

print("====================================")

#cria o array com um tipo específico
mtfloat = np.array([1,2,3],dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1,2,3],dtype = np.int32)
print(mtint)
print(type(mtint))

print("====================================")

#mudar o tipo do array
#transformar tipos de dados de arrays
mtnew = np.array([1.4,3.6,-5.1,9.42,4.99999])
print(mtnew)

#transformamos de float para int os valores são trucados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

print("====================================")

#inverso
mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

#mais de uma dimensão
#cria um matriz bidimesional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)

print("====================================")

vazio = np.empty([3,2],dtype=int)
print(vazio)
print("-------")
#cria uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)

#com valores igual a um
um = np.ones([5,7])
print(um)

#cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

print("====================================")

m = np.array([1,2,3,4,5,6])
print(m[1])

print(m[0:2])

print(m[1:])

print(m[-3:])

[12 34 26 18 10]
<class 'numpy.ndarray'>
====================================
[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>
====================================
[ 1.4      3.6     -5.1      9.42     4.99999]
[ 1  3 -5  9  4]
====================================
[1 2 3 4]
[1. 2. 3. 4.]
[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]
====================================
[[          393963700                   0]
 [7364561004907738157                  33]
 [          417436064     137381606391024]]
-------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
====================================
2
[1 2]
[2 3 4 5 6]
[4 5 6]

###Pandas

In [30]:
import pandas as pd

In [32]:
#carrega arquivo para dataframe Pandas
dados = pd.read_csv("Credit.csv")
#formato
dados.shape

#resumo estatístico de colunas numéricas
dados.describe()

,duration,credit_amount,installment_commitment,residence_since,age,existing_credits,num_dependents
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000

In [33]:
#primeiros registros
dados.head()

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,<0,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad

In [34]:
#últimos registros, com parâmetros
dados.tail(2)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
998,<0,45,'existing paid',radio/tv,1845,<100,1<=X<4,4,'male single',none,...,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad
999,0<=X<200,45,'critical/other existing credit','used car',4576,100<=X<500,unemployed,3,'male single',none,...,car,27,none,own,1,skilled,1,none,yes,good

In [35]:
#filtras por nome da coluna
dados[["duration"]]

     duration
0           6
1          48
2          12
3          42
4          24
..        ...
995        12
996        30
997        12
998        45
999        45

[1000 rows x 1 columns]

In [36]:
#filtrar linhas por indice
dados.loc[1:3]

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good

In [37]:
#linhas 1 e 3
dados.loc[[1,3]]

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good

In [38]:
#filtro
dados.loc[dados['purpose'] == "radio/tv"]

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
8,'no checking',12,'existing paid',radio/tv,3059,>=1000,4<=X<7,2,'male div/sep',none,...,'real estate',61,none,own,1,'unskilled resident',1,none,yes,good
12,0<=X<200,12,'existing paid',radio/tv,1567,<100,1<=X<4,1,'female div/dep/mar',none,...,car,22,none,own,1,skilled,1,yes,yes,good
15,<0,24,'existing paid',radio/tv,1282,100<=X<500,1<=X<4,4,'female div/dep/mar',none,...,car,32,none,own,1,'unskilled resident',1,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,0<=X<200,24,'critical/other existing credit',radio/tv,1743,<100,>=7,4,'male single',none,...,'life insurance',48,none,own,2,'unskilled resident',1,none,yes,good
991,'no checking',15,'all paid',radio/tv,1569,100<=X<500,>=7,4,'male single',none,...,car,34,bank,own,1,'unskilled resident',2,none,yes,good
992,<0,18,'existing paid',radio/tv,1936,'no known savings',4<=X<7,2,'male mar/wid',none,...,car,23,none,rent,2,'unskilled resident',1,none,yes,good
997,'no checking',12,'existing paid',radio/tv,804,<100,>=7,4,'male single',none,...,car,38,none,own,1,skilled,1,none,yes,good
998,<0,45,'existing paid',radio/tv,1845,<100,1<=X<4,4,'male single',none,...,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad

In [39]:
#outra condição
dados.loc[dados['credit_amount'] >  18000]

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
915,0<=X<200,48,'no credits/all paid',other,18424,<100,1<=X<4,1,'female div/dep/mar',none,...,'life insurance',32,bank,own,1,'high qualif/self emp/mgmt',1,yes,no,bad

In [40]:
#atribuimos resultado a variável, criando outro df
credito2 = dados.loc[dados['credit_amount'] >  18000]
print(credito2)

    checking_status  duration         credit_history purpose  credit_amount  \
915        0<=X<200        48  'no credits/all paid'   other          18424

    savings_status employment  installment_commitment       personal_status  \
915           <100     1<=X<4                       1  'female div/dep/mar'

    other_parties  ...  property_magnitude age  other_payment_plans housing  \
915          none  ...    'life insurance'  32                 bank     own

    existing_credits                          job num_dependents  \
915                1  'high qualif/self emp/mgmt'              1

     own_telephone foreign_worker class
915            yes             no   bad

[1 rows x 21 columns]

In [41]:
#definimos só algumas colunas
credito3 = dados[['checking_status','duration']].loc[dados['credit_amount'] >  18000]
print(credito3)

    checking_status  duration
915        0<=X<200        48

In [42]:
#séries, única coluna
# pode ser criada a partir de listas, array do numpy ou coluna de data frame
s1 = pd.Series([2,5,3,34,54,23,1,16])
print(s1)

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int64

In [43]:
#serie a partir de um array do numpy
import numpy as np
array1 = np.array([2,5,3,34,54,23,1,16])
s2 = pd.Series(array1)
print(s2)

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int64

In [45]:
#series a partir de um dataframe
s3 = dados['purpose']
print(s3)
type(s3)

0                 radio/tv
1                 radio/tv
2                education
3      furniture/equipment
4                'new car'
              ...
995    furniture/equipment
996             'used car'
997               radio/tv
998               radio/tv
999             'used car'
Name: purpose, Length: 1000, dtype: object

pandas.core.series.Series

In [44]:
#note a diferença, temos um data frame
d4= dados[['purpose']]
type(d4)

pandas.core.frame.DataFrame

In [46]:
#renomear
dados.rename(columns={"duration":"duração","purpose":"propósito"})

,checking_status,duração,credit_history,propósito,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,<0,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,'no checking',12,'existing paid',furniture/equipment,1736,<100,4<=X<7,3,'female div/dep/mar',none,...,'real estate',31,none,own,1,'unskilled resident',1,none,yes,good
996,<0,30,'existing paid','used car',3857,<100,1<=X<4,4,'male div/sep',none,...,'life insurance',40,none,own,1,'high qualif/self emp/mgmt',1,yes,yes,good
997,'no checking',12,'existing paid',radio/tv,804,<100,>=7,4,'male single',none,...,car,38,none,own,1,skilled,1,none,yes,good
998,<0,45,'existing paid',radio/tv,1845,<100,1<=X<4,4,'male single',none,...,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad
999,0<=X<200,45,'critical/other existing credit','used car',4576,100<=X<500,unemployed,3,'male single',none,...,car,27,none,own,1,skilled,1,none,yes,good

In [47]:
#porém a alteração não é persistida
dados.head(1)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good

In [48]:
#para persistir
dados.rename(columns={"duration":"duração","purpose":"propósito"},inplace=True)

In [49]:
#excluir coluna
dados.drop('checking_status',axis=1,inplace=True)
print(dados)

     duração                    credit_history            propósito  \
0          6  'critical/other existing credit'             radio/tv
1         48                   'existing paid'             radio/tv
2         12  'critical/other existing credit'            education
3         42                   'existing paid'  furniture/equipment
4         24              'delayed previously'            'new car'
..       ...                               ...                  ...
995       12                   'existing paid'  furniture/equipment
996       30                   'existing paid'           'used car'
997       12                   'existing paid'             radio/tv
998       45                   'existing paid'             radio/tv
999       45  'critical/other existing credit'           'used car'

     credit_amount      savings_status  employment  installment_commitment  \
0             1169  'no known savings'         >=7                       4
1             5951                <100      1<=X<4                       2
2             2096                <100      4<=X<7                       2
3             7882                <100      4<=X<7                       2
4             4870                <100      1<=X<4                       3
..             ...                 ...         ...                     ...
995           1736                <100      4<=X<7                       3
996           3857                <100      1<=X<4                       4
997            804                <100         >=7                       4
998           1845                <100      1<=X<4                       4
999           4576          100<=X<500  unemployed                       3

          personal_status other_parties  residence_since   property_magnitude  \
0           'male single'          none                4        'real estate'
1    'female div/dep/mar'          none                2        'real estate'
2           'male single'          none                3        'real estate'
3           'male single'     guarantor                4     'life insurance'
4           'male single'          none                4  'no known property'
..                    ...           ...              ...                  ...
995  'female div/dep/mar'          none                4        'real estate'
996        'male div/sep'          none                4     'life insurance'
997         'male single'          none                4                  car
998         'male single'          none                4  'no known property'
999         'male single'          none                4                  car

     age other_payment_plans     housing  existing_credits  \
0     67                none         own                 2
1     22                none         own                 1
2     49                none         own                 1
3     45                none  'for free'                 1
4     53                none  'for free'                 2
..   ...                 ...         ...               ...
995   31                none         own                 1
996   40                none         own                 1
997   38                none         own                 1
998   23                none  'for free'                 1
999   27                none         own                 1

                             job  num_dependents own_telephone foreign_worker  \
0                        skilled               1           yes            yes
1                        skilled               1          none            yes
2           'unskilled resident'               2          none            yes
3                        skilled               2          none            yes
4                        skilled               2          none            yes
..                           ...             ...           ...            ...
995         'unskilled resident'               1          none            yes
996  'high qualif/self emp/mgmt'               1           yes            yes
997                      skilled               1          none            yes
998                      skilled               1           yes            yes
999                      skilled               1          none            yes

    class
0    good
1     bad
2    good
3    good
4     bad
..    ...
995  good
996  good
997  good
998   bad
999  good

[1000 rows x 20 columns]

In [53]:
#verificar dados nulos
dados.isnull()

,duração,credit_history,propósito,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [52]:
#verificar dados nulos
dados.isnull().sum()

duração                   0
credit_history            0
propósito                 0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
personal_status           0
other_parties             0
residence_since           0
property_magnitude        0
age                       0
other_payment_plans       0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
foreign_worker            0
class                     0
dtype: int64

In [54]:
#preencher dados faltantes
dados['duração'].fillna(0,inplace = True)

/tmp/ipython-input-504353219.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dados['duração'].fillna(0,inplace = True)

In [55]:
#iloc
dados.iloc[0:3,0:5]

,duração,credit_history,propósito,credit_amount,savings_status
0,6,'critical/other existing credit',radio/tv,1169,'no known savings'
1,48,'existing paid',radio/tv,5951,<100
2,12,'critical/other existing credit',education,2096,<100

In [56]:
dados.iloc[[0,1,2,3,7],0:5]

,duração,credit_history,propósito,credit_amount,savings_status
0,6,'critical/other existing credit',radio/tv,1169,'no known savings'
1,48,'existing paid',radio/tv,5951,<100
2,12,'critical/other existing credit',education,2096,<100
3,42,'existing paid',furniture/equipment,7882,<100
7,36,'existing paid','used car',6948,<100